### ISSUE TITLE
Issue building in NSIS 1.9.1

### ISSUE THREAD

**Issue by ElSenorEd** [idleberg/vscode-nsis#5]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|nsis|idleberg|2.7.1|
|nsis-plugins|idleberg|1.0.5|
|svg-icons|idleberg|0.2.2|
|vscode-nsis|KrystofRiha|0.0.1|

Ctrl + B + Shift no longer works.  It was working in 1.7.2 version of VSCode.

Developer Console  log is here.

`mainThreadExtensionService.ts:110[C:/Users/Ed/.vscode/extensions/idleberg.nsis-2.7.1]: Unknown language in `contributes.snippets.language`. Provided value: haskellt.$localShowMessage @ mainThreadExtensionService.ts:110
extensionHost.ts:282[Extension Host] [C:/Users/Ed/.vscode/extensions/idleberg.nsis-2.7.1]: Unknown language in `contributes.snippets.language`. Provided value: haskelld.logExtensionHostMessage @ extensionHost.ts:282`

`extensionHost.ts:282[Extension Host] [C:/Users/Ed/.vscode/extensions/idleberg.nsis-2.7.1]: Unknown language in `contributes.snippets.language`. Provided value: haskelld.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] WARNING: Promise with no error callback:2`

`[Extension Host] WARNING: Promise with no error callback:2
extensionHost.ts:282[Extension Host] Object
shell.ts:437Cannot read property 'trim' of undefined: TypeError: Cannot read property 'trim' of undefined
    at C:\Users\Ed\.vscode\extensions\idleberg.nsis-2.7.1\lib\makensis.js:25:51
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:30381)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:1957)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3785)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3226)
    at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:17657)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16129)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:437
extensionHost.ts:282[Extension Host] TypeError: Cannot read property 'trim' of undefined
    at C:\Users\Ed\.vscode\extensions\idleberg.nsis-2.7.1\lib\makensis.js:25:51
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:30381)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:1957)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3785)
    at _completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:3226)
    at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:17657)
    at d (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:8:16129)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by idleberg** [comment]
Thanks for reporting, please update to v0.17.1

**Comment by idleberg** [comment]
Thanks for reporting. Could you please test the [latest commit](https://github.com/idleberg/vscode-nsis/blob/fa5000998921b15108fd1b2c98f58e3ef31e2f00/lib/makensis.js) before I publish it?
